_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.1
            "6": 4.45.2
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 2
epochs:
    value: 1
learning_rate:
    value: 0.0002
lora_alpha:
    value: 32
lora_r:
    value: 8
model_name:
    value: mistralai/Mistral-7B-v0.1
training_samples:
    value: 1000
validation_samples:
    value: 100
